language: node_js
node_js:
- '12.16'
addons:
  ssh_known_hosts: 139.59.216.92
before_install:
- openssl aes-256-cbc -K $encrypted_0ddd2445e49f_key -iv $encrypted_0ddd2445e49f_iv
  -in travis_rsa.enc -out travis_rsa -d
- chmod 600 travis_rsa
- mv travis_rsa ~/.ssh/id_rsa
- cd client
install:
- npm install
script:
- 'true'
after_success:
- npm run build
- cd ..
- bash ./deploy.sh
env:
  global:
  - secure: GLN4xzncQuFTkqq0ltt2PY8mRkcm6k1vu19gDyhyI883OdYBc6L2ZPQE4sUbMOLZI3Ug4pE/GF1tSxLV7YlRe/UVgbYegAoxmhbuii3f79dgSsVC6dglEDYFs0zdF3ZTfPJ3oq8OWvmwKS54yVT7AcsBsjrgTD28pIN0wj1GnzqqOOUWXGxOz1QMuY2gsOLtJuvcMLLCIAApn4Dc99wCwAC1Gtswe5RvETPMr4FHCKBrWlA1l6zEeAT+E+S6Pg44varjDQWQ5dvVYeIUwRjMk+2LPTsmwGA5MNqTnSWaS3qE8nJek5a0AY8SQQqgcKDDmO3L+VegC2i8nN3Hru2ZGFBNbDKQ7UAi9dDGp9QhRH0CtRS0e6JHWuqG8T8HbheicMte4WglIgO7FaML+kPZTNdbg1l4p01CUASjM+uItCm4T9xkReRWTQzUHYwsKTilBYmxahdQyiVBhH5dtroCkEjPbCp5gIKn3dmlmT7SdFwq48WhMiaOKlb2Vca2AuRWYTRiC2ilDBwGHHKDDSxfMtZyo8FBJL/SMCCYCiIOXggNPnVM05ePTEIBftWA7FoFis//s7qsEtmlLH+OAThLttmkLYZzX+Em9YMYFAv80SmcXFR7SIUcth3Gg1n7XLUijs9yvB3XRFjLpqOX1Sjl8EUwLzDR2wL3X4BvooLJdCM=
  - secure: rFCuR6MALmd/3cJCK2FisfcFHc8i2brSibb8TIZ5lzFKJYMssWz0SqjPyDUHcthRzwnFubjmr+H8i0TjImE0Pv+jJy2NYmOG+Cz9dOg+qQS/bnT+FjYTEUGTtmN763XwnvFXeki6KQyMtf2J3htREh/Z4ac3QgH1MU0IeP6Hk23FtyIwqJcTwO4bKGI2kkvo4BgWv38FwmYvek2p7ebIFTjl+S0weIL5wQlHgDA3FsizxypC+OVcfyyxy4k/+jdfqfMZcF6WpMyAuZzI+Gn8tcnKiIuBRnPNHl2Iz81QI7Pvv67yP67n2J7vZ1XY3UNR/6RQzmlHGx6u/h94Hg2WE34uXjVqiBS4bIlcXOQ6jtpBgjjgL6VX/xco+4S2D0+o0I4VNsTQwdTSoexOmsEaIg5KpILCWY8eVFS+b7uCeDCDz63M8218rMTM0PrZ2/YhNj+MPBEUSHowsbelY3/qbQ7s81rKpMKj/f32mseXEHvUEuQtBFqH8yf9gm1IsikrmG8AYxphHGKPnh5JhgBl2fGSkGaFjFfojjRefleQ0WiyOahvGSUZhEGIT6HWD+h6ZEqe0SsNDUrkmVIXtTeZGm+noTUGkPeXkHnNvM905cBxo/fF0Ny+TqacwCEfXwsgvdbmvbuYG+sKL+eGvhIJNym1NqGo3OOCgA7wab6/DKQ=
  - secure: KjpNHf0INovAet1tUBNyKZyRGcv2UctBZA3gH5CB/TnH3wIZrXdj087u4bppSKl1bTV5OtOQKEecICbiJTPOXNVAoaF1V+HRPO8uYzOAgW5kj8z/EMx4WWg6OovxStbtmpi0o/v7I3p3RsGDOEY3bcgMnIIHXqMKTp4jpxHzZkpvb8iNxJRpeb6yxiG+5CC9GCuN8U6pzeZDTT5YUexlr6OOiP5PsEK546zifHncRUYsXTUff8vCiK1I2tssPTYc1LFxFT65zwz8iYMumtWupoobDlpw3kvuDWxbz9Ztd+hauCXzHAgNarZLxMryB8KBF3QY8rQwfPzrdjja/a5ZVpS2fgn8cNf3wmAo25Oly7x5ulQISZzRfZu+4yyEfsJN/tKe+pMyhh1IFNiM7Iec0EZGNb1yKfnwrvoDsDoOzE3f/0njEHnsKb6lUoA10o+CQPefYD3dT85HLoueqKFvg+qWLKbx/+Gep16ZIO5ge5gMZi7r0RmaE4S375bSDiIfzy4Ot51LoesAMqKNn4LZmV8XRaowpw3f12gTt4MOYIThpI42qkkEq97ILE2RkTII5YvN2PbBeGACO8BMO9FWV5a7g6seQ6334h7mUrmUo+OIkK6G8piFGj2mOOuFpDAfONKvAo6Wl7jdo8/s+f+xyAaIUxHnYHrx8LTP2CM/PVw=
